# This file was generated by GoReleaser. DO NOT EDIT.
cask "pho" do
  version "0.1.48"

  on_macos do
    on_arm do
      sha256 "ee8864a27f6a405a688bf6fd88f8c5ec33e634db0f1ec0b4f40219c3d5c566d0"
      url "https://github.com/utkarsh261/pho/releases/download/v#{version}/pho_#{version}_macOS_arm64.tar.gz"
    end
    on_intel do
      sha256 "e1db387a833764940850eaa75222c7f856bcbf8a45866773250cf24cc971c01e"
      url "https://github.com/utkarsh261/pho/releases/download/v#{version}/pho_#{version}_macOS_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2694909801d0ff38f6418d2c102de7f84668dc540dafa2a977ce1990e1aecc6b"
      url "https://github.com/utkarsh261/pho/releases/download/v#{version}/pho_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2b26c1139eb6a7d0e43a38c3ac42bde177521f08ac5bb91d2f69d9f68d3df711"
      url "https://github.com/utkarsh261/pho/releases/download/v#{version}/pho_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pho"
  desc "A TUI for GitHub pull requests"
  homepage "https://github.com/utkarsh261/pho"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "gh",
    ]

  binary "pho"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pho"]
    end
  end

  # No zap stanza required
end
